version: 2.1

workflows:
  welcome:
    jobs:
      - build:
          context:
            - dockerhub-credentials

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run: echo 'ok'
