version: 2.1

orbs:
  welcome: circleci/welcome-orb@volatile

workflows:
  test:
    jobs:
      - build:
          context:
            - dockerhub-credentials
      - welcome/run:
          context:
            - dockerhub-credentials

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run: echo 'ok'
