version: 2.1

orbs:
  slack: circleci/slack@volatile

workflows:
  welcome:
    jobs:
      - slack/on-hold:
          context:
            - slack-notification
            - custom-templates
          template: CUSTOM_ON_HOLD
